const devs = [

    {
        id      :01,
        Name    :'asraful haq',
        skill   :'Mern stack',
        location: 'mirpur',
        age     : 20,
        photo   : 'https://www.nilphamari.info/wp-content/uploads/2016/08/Sohel-Passport-Size-New-Photo.jpg',
    },
    {
        id      :02,
        Name    :'Rabiul haq',
        skill   :'php',
        location: 'nator',
        age     : 50,
        photo   : 'http://jobs.hrbangladesh.com.bd/wp-content/uploads/job-manager-uploads/candidate_photo/2015/09/Passport-large.jpg',
    },
    {
        id      :03,
        Name    :'Israk Rifath',
        skill   :'Wordpress',
        location: 'Pabna',
        age     : 80,
        photo   : 'https://wub.edu.bd/admin-assets/images/employeeImg_thumb/passport_size_photo_(white_background).jpg',
    },
    {
        id      :04,
        Name    :'Imran',
        skill   :'wp',
        location: 'gulshan',
        age     : 180,
        photo   : 'https://www.ifa.org.uk/media/933127/Photo-of-Alii-Aqbour-Chowdhury.jpg',
    },
    {
        id      :05,
        Name    :'Samim',
        skill   :'Math',
        location: 'America',
        age     : 280,
        photo   : 'https://thumbs.dreamstime.com/z/biometric-passport-photo-young-blond-woman-neutral-facial-expression-biometric-passport-photo-young-woman-138523258.jpg',
    },
    {
        id      :06,
        Name    :'Ahsan',
        skill   :'Bangla',
        location: 'Australia',
        age     : 80,
        photo   : 'https://thumbs.dreamstime.com/z/frontal-biometric-passport-photo-young-blond-woman-112398558.jpg',
    },
    {
        id      :07,
        Name    :'Jonom',
        skill   :'Physic',
        location: 'Ataikula',
        age     : 40,
        photo   : 'https://thumbs.dreamstime.com/z/passport-photo-candid-young-blond-woman-104387009.jpg',
    },
    {
        id      :08,
        Name    :'Lutfor',
        skill   :'Chimistry',
        location: 'Gobinda',
        age     : 90,
        photo   : 'https://thumbs.dreamstime.com/z/beautiful-young-blonde-woman-white-background-id-identity-card-passport-driving-licence-167290778.jpg',
    },

]